// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACJjuUcaf44wVXTf6m63405ivjgab7eh0',
    appId: '1:295819328797:web:11a9e17aad4a649dfd35f4',
    messagingSenderId: '295819328797',
    projectId: 'ecommerce-app-26ebc',
    authDomain: 'ecommerce-app-26ebc.firebaseapp.com',
    storageBucket: 'ecommerce-app-26ebc.firebasestorage.app',
    measurementId: 'G-VSC2VLJCMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7QQPDzQwcrsuZ9IJBtuVCWvz6dDlEGqI',
    appId: '1:295819328797:android:223cf3c0a6687d35fd35f4',
    messagingSenderId: '295819328797',
    projectId: 'ecommerce-app-26ebc',
    storageBucket: 'ecommerce-app-26ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5q_U-5x8aOUiDu3qvioewbD1YI8C04is',
    appId: '1:295819328797:ios:209e50be235767eefd35f4',
    messagingSenderId: '295819328797',
    projectId: 'ecommerce-app-26ebc',
    storageBucket: 'ecommerce-app-26ebc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5q_U-5x8aOUiDu3qvioewbD1YI8C04is',
    appId: '1:295819328797:ios:209e50be235767eefd35f4',
    messagingSenderId: '295819328797',
    projectId: 'ecommerce-app-26ebc',
    storageBucket: 'ecommerce-app-26ebc.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACJjuUcaf44wVXTf6m63405ivjgab7eh0',
    appId: '1:295819328797:web:399ecc4ce51e66f9fd35f4',
    messagingSenderId: '295819328797',
    projectId: 'ecommerce-app-26ebc',
    authDomain: 'ecommerce-app-26ebc.firebaseapp.com',
    storageBucket: 'ecommerce-app-26ebc.firebasestorage.app',
    measurementId: 'G-K8MQQNG4TB',
  );
}
